# Site settings
title: The Laborer Post
email: yaz.khoury@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog as about all things related to Robotics and Artificial Intelligence news,
  as well as tutorials and opinion editorials regarding the future of the industry.
  Be sure to follow me on social media to get more updates about new content.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:3000/" # the base hostname & protocol for your site
twitter_username: Yazanator
github_username:  YazzyYaz

# Build settings
markdown: kramdown

source: ./_source
destination: ./_site

sass:
    sass_dir: _sass
    style: compressed
